export const SECURITY_SET_TOKEN = 'SECURITY_SET_TOKEN';
export const SECURITY_UNSET_TOKEN = 'SECURITY_UNSET_TOKEN';
export const SECURITY_RENEW_TOKEN = 'SECURITY_RENEW_TOKEN';
export const PROFILE_SET_USERINFO = 'PROFILE_SET_USERINFO';
